name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  publish_confluence:
    runs-on: ubuntu-latest
    name: Publish docs to confluence
    steps:
    - uses: actions/checkout@v2.0.0
    - name: publish to confluence
      uses: pratikmallya/publish-confluence@master
      with:
        username: ${{ secrets.atlassianUsername }}
        apitoken: ${{ secrets.atlassianApitoken }}
