name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: publish-confluence
      uses: pratikmallya/publish-confluence@v1.0
      with:
        username: ${{ secrets.atlassianUsername }}
        apitoken: ${{ secrets.atlassianApitoken }}
